site_name: rawfinder
repo_url: https://github.com/moskrc/rawfinder
site_url: https://moskrc.github.io/rawfinder
site_description: This script finds corresponded RAW files for JPEG images.
site_author: Vitalii Shishorin
edit_uri: edit/main/docs/
repo_name: moskrc/rawfinder
copyright: Maintained by <a href="https://moskrc.com">moskrc</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moskrc/rawfinder
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rawfinder

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
